---
- name: Converge
  hosts: all
  gather_facts: True
  connection: local

  vars:
    provider:
      ip_address: "{{ PA_login.ip_address }}"
      username: "{{ PA_login.username }}"
      password: "{{ PA_login.password }}"

  tasks:
    - name: Baseline the FW
      panos_baseline:
        provider: '{{ provider }}'

    - name: Create address object
      panos_skillet:
        skillet_path: "{{ playbook_dir }}/configurations"
        skillet: "happy_PANW_NM_000053"
        provider: '{{ provider }}'
      register: skillet_output

    - name: Debug skillet output
      debug:
        var: skillet_output

    - name: Call PaloAltoALGSTIG Role
      include_role:
        name: ../../../PaloAltoALGSTIG
      when:
        - device_make == "paloalto"
        - '"ALG" in device_role'
      tags:
      - always

    - name: Call PaloAltoIDPSSTIG Role
      include_role:
        name: ../../../PaloAltoIDPSSTIG
      when:
        - device_make == "paloalto"
        - '"IDPS" in device_role'
      tags:
      - always

    - name: Call PaloAltoNDMSTIG Role
      include_role:
        name: ../../../PaloAltoNDMSTIG
      when:
        - device_make == "paloalto"
        - '"NDM" in device_role'
      tags:
      - always
