name: happy_PANW_NM_000053
label: STIG PANW-NM-000053
description: Password complexity of 15 or more
type: panos
labels:
    collection:
      - stig
      - Validation

variables: []

snippets:
  - name: pass-password-complexity-length
    xpath: /config/mgt-config
    element: |-
        <password-complexity>
              <minimum-length>15</minimum-length>
        </password-complexity>